# Generated by Django 3.2.19 on 2023-07-22 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_post_topico'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='topico',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='post',
            name='userID',
        ),
    ]
